- hosts: localhost
  sudo: yes
  remote_user: vagrant
  tasks:
  - name: Actualizar sistema
    apt: update_cache=yes upgrade=dist
  - name: Instalar python-setuptools
    apt: name=python-setuptools state=present
  - name: Instalar build-essential
    apt: name=build-essential state=present
  - name: Instalar pip
    apt: name=python-pip state=present
  - name: Instalar git
    apt: name=git state=present
  - name: Ins Pyp
    apt: pkg=python-pip state=present
  - name: Instalar python-dev
    apt: pkg=python-dev state=present
  - name: Obtener aplicacion de git
    git: repo=https://github.com/sn1k/submodulo-alberto.git  dest=submodulo-alberto clone=yes force=yes
  - name: Permisos de ejecucion
    command: chmod -R +x submodulo-alberto
  - name: Instalar requisitos
    command: sudo pip install -r submodulo-alberto/requirements.txt
  - name: ejecutar
    command: nohup sudo python submodulo-alberto/manage.py runserver 0.0.0.0:80
    
    
